### ISSUE TITLE
Current release is not up to date

### ISSUE THREAD

**Issue by shadowhand** [BRITEWEB/capistrano-gulp#5]
588ab9cd1e0f35b1f09bcadbcdcf995defdb06cc is not included in 0.0.1. The only way to use this option is with a `master` branch install.

**Comment by oversee-ffleming** [comment]
A quick push to Rubygems would be the bees' knees! Thanks!

**Comment by philbates35** [comment]
+1 A new release would be very useful.

**Comment by alebiavati** [comment]
Hi there,

sorry about the crazy delay on this. For some reason I was not getting notifications on the issues posted here.

Anyway, I just pushed v0.0.2 to rubygems with all the latest pull requests.
